### ISSUE TITLE
Is. there any way to improve the quality of video?

### ISSUE THREAD

**Issue by davidortiz313** [dmnsgn/canvas-record#10]
I was trying to export threejs scene into mp4, but the quality is not good.
Please let me know if there is any way to improve it.

**Comment by dmnsgn** [comment]
One of the most important encoderOptions to improve quality is [bitrate](https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder/configure#bitrate).

It is currently guestimated in [estimateBitRate](https://github.com/dmnsgn/canvas-record/blob/55535c8e0bd1820d66b556d5ac6fafbbebff314a/src/utils.js#L69-L84) but it is really dependent on the type of video you are exporting (eg. animated vector graphics don't require the same bitrate as realistic scene with environment map).

**Comment by arcman7** [comment]
In a hypothetical scenario, say we're rendering a real life video filmed in 4k (very realistic) to the canvas, and for whatever reason we want to re-export that video using canvas-record, we would aim to use the highest possible bitrate? If the canvas were of size 500x500 pixels, would we just need a bitrate capable of capturing the entirety of that canvas on each frame? Or is there some nifty tricks being done under the hood that utilize key-frames?
