### ISSUE TITLE
RecorderOptions.extension is boolean?

### ISSUE THREAD

**Issue by Kalabasa** [dmnsgn/canvas-record#12]
**Bug:** `RecorderOptions.extensions` property is typed as a `boolean` in library jsdoc and in the README docs.

However, it seems to expect a string instead.

**Solution:** Change type to `string`

**Workaround:** Cast to `any` as in `new Recorder(ctx, { extension: 'gif' as any })`

**Comment by dmnsgn** [comment]
Available in [v5.0.0-beta.0](https://github.com/dmnsgn/canvas-record/releases/tag/v5.0.0-beta.0)
