### ISSUE TITLE
Provide bundled/minified file for CDN support

### ISSUE THREAD

**Issue by vincerubinetti** [dmnsgn/canvas-record#17]
Would be nice to be able to use this library from a script tag, from an npm cdn, e.g. https://unpkg.com/canvas-record@latest

**Comment by dmnsgn** [comment]
unpkg has not been the best for ESM packages to be honest. I'd recommend https://esm.sh/ and its different options (?bundle-deps, ?no-bundle...):

```html
<script type="module">
  import {
    Recorder,
    RecorderStatus,
    Encoders,
  } from "https://esm.sh/canvas-record@5.0.0";
</script>
```
