### ISSUE TITLE
is audio supported?

### ISSUE THREAD

**Issue by xeoshow** [dmnsgn/canvas-record#18]
Hi, 

Just would like to know: when I am recording, I also have a background music which should be recorded, is this supported? 
Thanks a lot.

**Comment by dmnsgn** [comment]
Hi,

I don't intend to support Audio just yet, unless it can be added without increasing the complexity of the encoders. [mp4-muxer demo](https://github.com/Vanilagy/mp4-muxer/blob/main/demo/script.js) and extending the [WebCodecsEncoder](https://github.com/dmnsgn/canvas-record/blob/main/src/encoders/WebCodecsEncoder.js) would be a good place to start, but so far I have managed by merging audio and video on the file system after the export with ffmpeg.

**Comment by merlindru** [comment]
@dmnsgn Is there any way to get access to the muxer? I'm seeing mp4-muxer has methods to add audio data, but I'm not sure how to access those methods

**Comment by dmnsgn** [comment]
> @dmnsgn Is there any way to get access to the muxer? I'm seeing mp4-muxer has methods to add audio data, but I'm not sure how to access those methods

For the WebCodecsEncoder, you can pass `muxerOptions` and the muxer is added to the instance:
https://github.com/dmnsgn/canvas-record/blob/347bdff4c49bd5941d2f483198c45321aeff82af/src/encoders/WebCodecsEncoder.js#L94

So something like:
```js
const audioSampleRate = 44100;
const encoder = new Encoders.WebCodecsEncoder({
  muxerOptions: {
    codec: 'aac',
    sampleRate: audioSampleRate,
    numberOfChannels: 1
  }
})

const { muxer } = encoder;

const audioEncoder = new AudioEncoder({
  output: (chunk, meta) => muxer.addAudioChunk(chunk, meta),
  error: e => console.error(e)
});
audioEncoder.configure({
  codec: 'mp4a.40.2',
  numberOfChannels: 1,
  sampleRate: audioSampleRate,
  bitrate: 128000
});

// ... use the audioEncoder to write data
// ... overwrite encoder.encode to add await audioEncoder.flush() after await this.encoder.flush();
```
