### ISSUE TITLE
error for canvas with a size not a multiple of 2

### ISSUE THREAD

**Issue by ipfedor** [dmnsgn/canvas-record#19]
for exist canvas with size 1920x945 throw error 

ERROR h264-mp4-encoder.cpp(244): Incorrect buffer size for RGBA (width * height * 4)

with size 1024x768 - worked

**Comment by dmnsgn** [comment]
That's actually a limitation with [h264-mp4-encoder](https://github.com/TrevorSundberg/h264-mp4-encoder?tab=readme-ov-file#api):
```
     * Width of the input frames and output video. Must be a multiple of 2. Required.
     * Height of the input frames and output video. Must be a multiple of 2. Required.
```
